#!/bin/zsh
# Enable antigen (http://antigen.sharats.me)
# By Glenn 'devalias' Grant (devalias.net)

echo "Loading antigen.."

if [[ ! -x $(which brew) ]]; then
  echo "  ERROR: Antigen loader requires homebrew to be installed. Exiting."
  return 1
fi

# Paths to check
antigen_path1="$(brew list antigen | grep antigen.zsh)"
antigen_path2="$(brew --prefix)/Cellar/antigen/1/share/antigen.zsh"

if [[ -e $antigen_path1 ]]; then
  antigen_path="$antigen_path1"
elif [[ -e $antigen_path2 ]]; then
  antigen_path="$antigen_path2"
else
  echo "  ERROR: Antigen not found. Was it installed with homebrew? Skipping. ($antigen_path1, $antigen_path2)"
  return 1
fi

source $antigen_path

# Load oh-my-zsh (http://ohmyz.sh/)
antigen use oh-my-zsh

# All of our (unique) antigen files
typeset -U antigen_files
antigen_files=($ZSH/**/*.anti)

# Load antigen files
for file in ${antigen_files}
do
  echo "  $file"
  source $file
done

# Load completions
antigen bundle zsh-users/zsh-completions src

# Bundles from the default repo
#   Ref: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins
#antigen bundle aws
#antigen bundle common-aliases
#antigen bundle encode64
#antigen bundle gitfast
#antigen bundle github
#antigen bundle history
#antigen bundle jsontools
#antigen bundle osx
#antigen bundle sbt
#antigen bundle scala
#antigen bundle sublime
#antigen bundle vagrant
#antigen bundle web-search
#antigen bundle wd

# Load the theme
#antigen theme robbyrussell
#antigen theme amuse
#antigen theme dallas
antigen theme pygmalion
#antigen theme sunrise

# Tell antigen we're done
antigen apply