#!/usr/bin/env zsh
# Enable antigen (http://antigen.sharats.me)
# By Glenn 'devalias' Grant (devalias.net)

# Import our common helper scripts
source "${ZSH}/lib/_helpers"

echo "Loading antigen.."

if ! is_installed "brew" 1> /dev/null; then
  echo "  [ERROR] Antigen loader requires homebrew to be installed. Exiting."
  return 1
fi

# Paths to check
antigen_path1="$(brew --prefix)/share/antigen/antigen.zsh"
antigen_path2="$(brew list antigen | grep antigen.zsh)"

if [[ -e $antigen_path1 ]]; then
  antigen_path="$antigen_path1"
elif [[ -e $antigen_path2 ]]; then
  antigen_path="$antigen_path2"
else
  echo "  ERROR: Antigen not found. Was it installed with homebrew? Skipping. ($antigen_path1, $antigen_path2)"
  return 1
fi

source $antigen_path

if [[ "$1" == "update" ]]; then
  echo "Updating antigen.."
  antigen update
  echo "Antigen updated."
  exit 0
fi

# Load oh-my-zsh (http://ohmyz.sh/)
antigen use oh-my-zsh

# All of our (unique) antigen files
typeset -U antigen_files
antigen_files=($ZSH/**/*.anti)

# Create a function we can call later to see what was loaded
list_antigen_files() {
  echo "Custom antigen files loaded for $ZSH:"
  for file in ${antigen_files}; do
    echo "  $file"
  done
}

# And alias the function to start with antigen_ so we can remember how to find it
antigen_list_files() { list_antigen_files }

# Load antigen files
for file in ${antigen_files}
do
  echo "  $file"
  source $file
done

# Load completions
antigen bundle zsh-users/zsh-completions src

# Bundles from the default repo
#   Ref: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins
#antigen bundle aws
antigen bundle common-aliases
#antigen bundle encode64
#antigen bundle gitfast
antigen bundle github
#antigen bundle history
#antigen bundle jsontools
#antigen bundle sbt
#antigen bundle scala
#antigen bundle vagrant
#antigen bundle web-search
#antigen bundle wd

# Load the theme
#antigen theme robbyrussell
#antigen theme amuse
#antigen theme dallas
antigen theme pygmalion
#antigen theme sunrise

# Tell antigen we're done
antigen apply

echo "Antigen done!"
