# Homebrew
alias brew-dir="cd $(brew --prefix) && pwd"
alias brew-cellardir="cd $(brew --cellar) && pwd"
alias brew-cachedir="cd $(brew --cache) && pwd"
alias brew-tapsdir="cd $(brew --prefix)/Homebrew/Library/Taps && pwd"
alias brew-tapsdir-homebrew="cd $(brew --prefix)/Homebrew/Library/Taps/homebrew/ && pwd"
alias brew-tapsdir-core="cd $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core/Formula && pwd"
alias brew-tapsdir-cask="cd $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks && pwd"
alias brew-add="echo Try one of: 'brew create -h', brew-new-formula, brew-new-cask"
alias brew-new-formula="echo 'brew create --help\nbrew-tapsdir-core\nbrew style --fix FORMULA\nbrew audit --new FORMULA\nbrew audit --online FORMULA\nbrew audit --strict FORMULA\ngit new-branch 0xdevalias/add-formula-FORMULA\ngit remote add 0xdevalias git@github.com:0xdevalias/homebrew-core.git\ngh pr create --repo homebrew/homebrew-core --web\nTODO: add more/better instructions/automations here.. See also this PR I created, and might be usable as a reference: https://github.com/Homebrew/homebrew-core/pull/120044\nOr all my PRs: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+author%3A0xdevalias'"
alias brew-new-cask="echo 'brew create --help\nbrew-tapsdir-cask\nbrew style --fix CASK\nbrew audit --new-cask CASK\nbrew audit --cask --online CASK\nTODO: add more/better instructions/automations here.. See also this PR I created, and might be usable as a reference: https://github.com/Homebrew/homebrew-cask/pull/138933\nOr all my PRs: https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+author%3A0xdevalias'"
alias brew-commands="brew commands"
