# if (( $+commands[starship] )); then
#   # https://github.com/starship/starship/issues/2806
#   #   _arguments:comparguments:325: can only be called from completion function
#   #
#   #   https://github.com/starship/starship/issues/2806#issuecomment-864547912
#   #     zsh completions generated by Starship is not directly source-able. You have multiple options:
#   #       If you installed Starship (and perhaps zsh) from the same package manager, it should already be taken care of. This is the most case.
#   #       Some zsh plugins/managers may also deal with the hassle.
#   #       Generate and put the completion script into $fpath. Instructions.
#   #       Or, let's make the script source-able
#   #
#   #   https://github.com/starship/starship/issues/2806#issuecomment-1399419171
#   #     This references a few other comments/resources that explain things further, but basically:
#   #       We can make it directly sourceable by removing the last line with `sed '$d'`, and then add in `compdef _starship starship`
#   #       But we probably don't even need to do that, because our package manager likely did it for us already.
#   #       eg. Homebrew does: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/starship.rb
#   source <(starship completions zsh | sed '$d')
#   compdef _starship starship
# fi
